version: '3'

services:
  mosquitto:
    image: eclipse-mosquitto:latest
    restart: unless-stopped
    ports:
        - 1883:1883
    volumes:
        - ./mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
        